"""poets and poems

Revision ID: b958a870006a
Revises: 
Create Date: 2020-10-08 02:19:36.908524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b958a870006a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dynasty', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poet_name'), 'poet', ['name'], unique=False)
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('poem', sa.String(length=500), nullable=True),
    sa.Column('poet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poet_id'], ['poet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poem_title'), 'poem', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poem_title'), table_name='poem')
    op.drop_table('poem')
    op.drop_index(op.f('ix_poet_name'), table_name='poet')
    op.drop_table('poet')
    # ### end Alembic commands ###
